name: Oura Sleep Check

on:
  # Daily schedule - GitHub Actions uses UTC time
  # Default: 12:00 UTC = 8:00 AM EDT (New York during Daylight Saving Time)
  schedule:
    - cron: '0 12 * * *'
  
  # Alternative cron schedules for EST/EDT transitions:
  # For 8:00 AM EDT (Daylight Saving Time, ~March-November): '0 12 * * *' (12:00 UTC)
  # For 8:00 AM EST (Standard Time, ~November-March): '0 13 * * *' (13:00 UTC)
  # Adjust the active cron line above when DST changes if exact local time is critical.
  
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  check-sleep:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run Oura sleep check
        env:
          OURA_TOKEN: ${{ secrets.OURA_TOKEN }}
          POKE_WEBHOOK_URL: ${{ secrets.POKE_WEBHOOK_URL }}
          # Optional: override threshold defaults
          SLEEP_SCORE_THRESHOLD: ${{ secrets.SLEEP_SCORE_THRESHOLD }}
          MIN_TOTAL_SLEEP_MIN: ${{ secrets.MIN_TOTAL_SLEEP_MIN }}
          MAX_SLEEP_LATENCY_MIN: ${{ secrets.MAX_SLEEP_LATENCY_MIN }}
          POOR_NIGHTS_STREAK: ${{ secrets.POOR_NIGHTS_STREAK }}
          TIMEZONE: ${{ secrets.TIMEZONE }}
        run: node index.mjs
